config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :recipes
root "recipes#index"
  
end

app/models/cuisine.rb
class Cuisine < ActiveRecord::Base
has_many :recipes,:dependent => :destroy

end

app/models/food_preference.rb
class FoodPreference < ActiveRecord::Base
has_many :recipes,:dependent => :destroy

end

app/models/food_type.rb
class FoodType < ActiveRecord::Base
has_many :recipes,:dependent => :destroy
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
belongs_to :cuisine
belongs_to :food_type
belongs_to :food_preference
DIFFICULTY=%w(Easy Medium Hard)
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #helper_method :sidebar_values
 before_action :sidebar_values
 # if we use helper method we can pass that method in root action
# recipe controller index action
def sidebar_values
  @food_types = FoodType.all
  @food_preferences = FoodPreference.all
  @cuisines = Cuisine.all
end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  before_action :set_recipe, :except => [:index,:new,:create]
before_action :authenticate_user!, :except => [:index,:show]
  def index
    @recipes = Recipe.all
   # sidebar_values
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      redirect_to recipes_path
    else
      render :new
    end
  end
  
  def edit
  end

  def update
    if @recipe.update(recipe_params)
      redirect_to recipes_path
    else
      render :edit
    end
  end



  def show
  end

  def destroy
   @recipe.destroy
   redirect_to recipes_path
 end

 private

 def set_recipe
  @recipe = Recipe.find(params[:id])
end

def recipe_params
  params.require(:recipe).permit!
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Curreynation</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<ul class="nav navbar-nav pull-right">
  <% if user_signed_in? %>
  <li><%= link_to "Signout",destroy_user_session_path, :method => :delete %></li>
  <%else%>
  <li class="active"><%= link_to "Signin",new_user_session_path %></li>
  <li class="active"><%= link_to "SignUp",new_user_registration_path %></li>
  <%end%>
  </ul>




<div class="row">
<div class="col-lg-2">

<div class="panel panel-primary" id="panels">
<div class="panel-heading">Food Preferences
</div>
<% @food_preferences.each do |fp| %>
<p><%= fp.name%></p>
<%end%>
</div>


<div class="panel panel-primary" id="panels">
<div class="panel-heading">Food Type
</div>
<% @food_types.each do |ft| %>
<p><%= ft.name%></p>
<%end%>
</div>
<div class="panel panel-primary" id="panels">
<div class="panel-heading">Cuisine
</div>
<% @cuisines.each do |c| %>
<p><%= c.name%></p>
<%end%>
</div>
</div>
<div class="col-lg-9">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>
</div>
</div>

</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>


<div class="form-group">
<%= f.label :Title %>
<%= f.text_field :title,:class => "form-control" %>
</div>


<div class="form-group">
<%= f.label :DificultyLevel %>
<%= f.select :dificulty_level, Recipe::DIFFICULTY,{},:class => "form-control" %>



</div>

<div class="form-group">
<%= f.label :ingrediants %>
<%= f.text_area :ingrediants,:class => "form-control" %>
</div>

<div class="form-group">
<%= f.label :procedure %>
<%= f.text_area :procedure,:class => "form-control" %>
</div>

<div class="form-group">
<%= f.label :cookingtime %>
<%= f.text_field :cookingtime,:class=>"form-control" %>
</div>

<div class="form-group">
<%= f.label :cuisine_id %>
<%= f.select(:cuisine_id,
options_from_collection_for_select(Cuisine.all,
:id, :name), {:prompt => 'Please Choose'}, :class =>
"form-control") %>
</div>


<div class="form-group">
<%= f.label :food_type_id %>
<%#= f.select :food_type_id, options_for_select([["select",""]] + FoodType.all.map{|e| [e.name,e.id]} ) %>
<%= f.select(:food_type_id,options_from_collection_for_select(FoodType.all,:id,:name),{:prompt => 'Please select FoodType'},:class => "form-control")%>
</div>


<div class="form-group">
<%= f.label :food_preference_id %>
<%= f.select(:food_preference_id, options_from_collection_for_select(FoodPreference.all,:id,:name),{:prompt => 'Please Select FoodPreference'},:class => "form-control") %>
</div>

<div class="form-action">
<%= f.submit %>
</div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Edit Recipe</h1>
<p><%= render "form" %></p>
<%= link_to "Back", recipes_path %>

app/views/recipes/index.html.erb
<table class="table table-striped" style="background:white;">
  <tr>
    <th>Title</th>
    <th>DificultyLevel</th>
    <th>Ingredients</th>
    <th>Procedure</th>
    <th>cookingtime</th>
    <th>Cuisine Name</th>
    <th>FoodType</th>
    <th>FoodPreference</th>
    <th>Actions</th>
  </tr>
  <% @recipes.each do |recipe| %>
  <tr>

    <td><%= recipe.title %></td>
    <td><%= recipe.dificulty_level %></td>
    <td><%= recipe.ingrediants %></td>
    <td><%= recipe.procedure %></td>
    <td><%= recipe.cookingtime %></td>
    <td><%= recipe.cuisine.name%></td>
    <td><%= recipe.food_type.name%></td>
    <td><%= recipe.food_preference.name%></td>

    <td>
        <%= link_to "Show", recipe_path(recipe), :class => "btn btn-success" %>
        <% if user_signed_in? %>    <%= link_to "Edit", edit_recipe_path(recipe), :class => "btn btn-warning" %>|
<%= link_to "Delete",recipe_path(recipe),:method => :delete, :data => {:confirm => "are you sure?"}, :class => "btn btn-danger" %>
<%end%>  </td>
    </tr>
  <% end %>
  </table>









  <%= link_to "New", new_recipe_path, :class => "btn btn-default" %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>
<p><%= render "form" %></p>

<%= link_to "Back", recipes_path %>

app/views/recipes/show.html.erb
<h1>Recipe</h1>
<p>Title</p>
 <%= @recipe.title %>

   <p>Dificulty Level: <%= @recipe.dificulty_level %></p>

   <p>Ingredients: <%= @recipe.ingrediants %></p>

<p>Procedure:<%= @recipe.procedure %></p>

   <p>CookingTime: <%= @recipe.cookingtime %></p>

   <p>CuisineType :<%= @recipe.cuisine.name%></p>

   <p>FoodType :<%= @recipe.food_type.name%></p>

   <p>FoodPreference :<%= @recipe.food_preference.name%></p>